#!/bin/sh
exec 1>&2
# enable user input
exec < /dev/tty

consoleregexp='console.log'
if test $(git diff --cached | grep $consoleregexp | wc -l) != 0
then 
  exec git diff --cached | grep -ne $consoleregexp
  read -p "There are some occurrences of console.log at your modification. Are you sure want to continue? (y/n)" yn
  echo $yn | grep ^[Yy]$
  if [ $? -ne 0 ] 
  then
    exit 1;
  fi
fi

yarn test
if [ $? -ne 0 ] 
then 
  read -p "Some tests failed. Are you sure want to continue? (y/n)" yn
  echo $yn | grep ^[Yy]$
  if [ $? -ne 0 ] 
  then
    exit 1;
  fi
fi
